// <auto-generated />
using System;
using FTMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FTMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FtmsDbContext))]
    [Migration("20260826224846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FTMS.Domain.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("TransactionStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TransactionType");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("TransactionDate")
                        .IsDescending()
                        .HasDatabaseName("IX_Transactions_TransactionDate");

                    b.HasIndex("TransactionStatusId")
                        .HasDatabaseName("IX_Transactions_TransactionStatusId");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .HasDatabaseName("IX_Transactions_CreatedAtUtc");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CreatedAtUtc", "Id"));

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Amount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("FTMS.Infrastructure.Persistence.Entities.TransactionAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("TransactionId", "ChangedAtUtc")
                        .HasDatabaseName("IX_TransactionAudits_TransactionId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("TransactionId", "ChangedAtUtc"));

                    b.ToTable("TransactionAudits", (string)null);
                });

            modelBuilder.Entity("FTMS.Infrastructure.Persistence.Entities.TransactionStatusLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StatusName")
                        .IsUnique()
                        .HasDatabaseName("UQ_TransactionStatuses_StatusName");

                    b.ToTable("TransactionStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                            StatusName = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-4000-8000-000000000002"),
                            StatusName = "Inactive"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-4000-8000-000000000003"),
                            StatusName = "Pending"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-4000-8000-000000000004"),
                            StatusName = "Completed"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-4000-8000-000000000005"),
                            StatusName = "Cancelled"
                        });
                });

            modelBuilder.Entity("FTMS.Domain.Transactions.Transaction", b =>
                {
                    b.HasOne("FTMS.Infrastructure.Persistence.Entities.TransactionStatusLookup", null)
                        .WithMany()
                        .HasForeignKey("TransactionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_TransactionStatuses");

                    b.OwnsOne("FTMS.Domain.Transactions.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(3)")
                                .HasDefaultValue("ZAR")
                                .HasColumnName("CurrencyCode");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("FTMS.Infrastructure.Persistence.Entities.TransactionAudit", b =>
                {
                    b.HasOne("FTMS.Domain.Transactions.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TransactionAudits_Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
